apiVersion: apps/v1
kind: Deployment
metadata:
  name: wils-playground
  namespace: dev
  labels:
    app: wils-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wils-playground
  template:
    metadata:
      labels:
        app: wils-playground
    spec:
      containers:
        - name: playground
          image: "wil42/playground:v1"
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wils-service
  namespace: dev
spec:
  selector:
    app: wils-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wils-service
  namespace: dev
spec:
  entryPoints:
    specificIPv4:
      address: "192.168.42.20:8888"
  routes:
  - kind: Rule
    match: PathPrefix(`/`)
    services:
    - name: wils-service
      port: 8888

